name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "6 5 * * *"

jobs:
  verify:
    uses: kapricorn-media/github/workflows/verify.yaml@main